name: Simple Python CI

on: [push]   # run this on every push

jobs:
  test:
    runs-on: ubuntu-latest   # GitHub gives you a fresh computer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest
